namespace ConsoleApp1.Enumerations
{
    internal static class Clés
    {
        internal static string PublicKey => @"BgIAAACkAABSU0ExAAgAAAEAAQAVikZCnxWu2/rSdmd9U3fnfN9bgBaIsU24FZS3yHIGEsrMo+nebv
                    TNV9bbi5JmqPaJaJi48olwlKuu4kQeG+5lqnbTNrOoK0Tw9JDHv4eaPXnkgJkcwVSloTsS4ItiCQIClqM2GU
                    QtJdaGEAhCnzIWHQMVPczxi4848hFMVXjNUD7wqcsVYT4vtYNNJ0WwQi6kZdfmPryQ4sEFNWCIEnM9oImSLI
                    SlAWrBwxedXEajAjDWo1rOCUt4Hbyx/v6il5LL429NB1oygbaveM68R7gylvwUHo9mS4ZFoKMW/kYYH8scDv
                    N/tviBt8/Bu1vF6anoZgwLIs9nAS4Q4xrrxpOe";

        internal static string TextAEncrypter => @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et imperdiet erat, nec malesuada neque. Nam dignissim, nisl id lobortis bibendum, dui massa tincidunt sapien, nec dignissim purus nunc vel massa. Nullam lectus purus, fermentum at justo eget, eleifend rhoncus tellus. Vivamus tempor orci pellentesque, eleifend elit sed, pellentesque turpis. Nam eget dui id massa malesuada tincidunt non vel nisl. Ut finibus libero eget neque aliquet, ut pulvinar magna tincidunt. Etiam ut auctor nunc, at aliquet leo. Aliquam id elit sit amet dolor hendrerit efficitur. Fusce elementum ornare nisi eu suscipit. Cras nec augue eu lorem dapibus semper. Proin sapien quam, blandit et cursus a, accumsan nec tortor.

Nunc sit amet blandit leo. Vestibulum placerat viverra ex, eu accumsan ex viverra vitae. Quisque non imperdiet orci. In accumsan porttitor nunc eget volutpat. Donec tincidunt pellentesque urna, ac convallis lorem finibus egestas. Nulla vel orci vel neque aliquam molestie. Ut id ex sit amet lectus fermentum ultricies eget at mi. Donec finibus ornare sem, vitae suscipit velit dictum vel. Vestibulum commodo non justo et fermentum. Morbi vehicula bibendum dui. Morbi mi turpis, vehicula id est non, interdum ultrices tortor. Curabitur nibh magna, sollicitudin at elementum nec, feugiat quis tellus. Quisque vel ex hendrerit, aliquam ipsum sit amet, condimentum massa. Vivamus aliquam, eros ut euismod tristique, elit enim lobortis lacus, quis rutrum tortor dolor nec mi. Sed leo enim, condimentum quis vulputate vel, malesuada id est.

Pellentesque fermentum id leo fringilla hendrerit. Ut ultricies libero leo, pharetra hendrerit metus egestas quis. Donec scelerisque luctus enim, sed molestie neque venenatis vitae. Vestibulum a ligula volutpat, dictum purus sed, molestie orci. Integer neque massa, convallis vel pulvinar vitae, vehicula non ex. Cras laoreet accumsan tincidunt. Maecenas id interdum est. Pellentesque ut tincidunt risus. Nunc consequat lectus non mauris pellentesque, eget faucibus nibh tempus. Phasellus mauris tortor, tincidunt sit amet elit non, iaculis pharetra neque. Curabitur et convallis eros. Pellentesque massa dolor, rhoncus vulputate sem et, cursus vestibulum leo. Duis non tincidunt nisl. Nam auctor egestas ex sagittis suscipit. Proin in maximus odio.

Morbi venenatis elit in viverra tempor. Integer viverra purus nunc, vulputate porttitor nisl lobortis a. Donec pellentesque dictum mauris id tempus. Donec ullamcorper erat a orci efficitur, vitae venenatis risus varius. Donec facilisis tellus eget risus sagittis sagittis. Sed pharetra massa dolor, ut laoreet libero efficitur ac. Donec volutpat ante blandit gravida dignissim. Fusce id ante interdum, suscipit turpis nec, pellentesque odio. Cras rutrum ultricies volutpat. Phasellus aliquet tempor nisi, et pulvinar mi imperdiet eget.

Morbi justo risus, convallis non lacus sed, ullamcorper interdum metus. Pellentesque posuere erat id augue maximus, ac molestie ante vestibulum. Aenean varius tempus sollicitudin. Praesent efficitur erat nisl, vitae mattis purus faucibus sit amet. Nunc sed maximus mauris, ut rutrum ipsum. Aliquam maximus risus ut nibh tincidunt, sit amet laoreet neque pellentesque. Integer interdum mollis felis in porta. Etiam iaculis lacus mauris, non interdum quam condimentum vitae. Donec et luctus metus.

Aenean vulputate diam eget odio feugiat varius. Nullam enim justo, placerat vitae dictum et, mattis ut elit. Integer ultrices felis ut mattis blandit. Etiam gravida ligula quis est laoreet, non accumsan tortor iaculis. Vestibulum non nisi eget ipsum facilisis cursus et dapibus purus. Morbi nec fringilla velit, eu iaculis justo. Duis vestibulum, nisl vitae dictum euismod, eros eros tristique orci, in cursus nibh enim sed libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi non tortor at sem bibendum hendrerit sit amet at turpis. Morbi ut ligula eget magna ullamcorper egestas vel posuere metus. Morbi congue faucibus tellus, et varius est pellentesque quis. Morbi ac venenatis dui. Curabitur eleifend eros dui, sed tincidunt dolor efficitur sed.

Duis eleifend enim eget urna tempus lacinia. Proin in ultricies nunc, eu malesuada erat. Fusce eu suscipit velit, nec posuere justo. Nunc posuere nunc orci, eu porttitor ligula hendrerit at. Duis rutrum pulvinar leo, in gravida velit placerat et. Suspendisse vehicula pulvinar augue, in vestibulum orci pharetra quis. Suspendisse ex metus, dapibus sed mi quis, gravida varius ante. Nullam dignissim dui nec justo imperdiet pharetra. Mauris sit amet posuere diam.

Pellentesque auctor iaculis ligula sed faucibus. Curabitur eget eros posuere, venenatis est et, molestie elit. Sed at justo quam. Etiam congue turpis at viverra semper. Suspendisse finibus nec elit vel ornare. Duis facilisis elit risus, id facilisis urna consequat vel. Nam vehicula dolor sapien, non semper mi faucibus ac.

Proin porta imperdiet nulla, vel pellentesque neque tempor id. Nulla eleifend egestas tellus, nec rutrum lacus consequat nec. Integer consectetur turpis eu est mattis vulputate. Ut non nisi sed magna feugiat fringilla quis et ligula. Aenean eget dui sed metus facilisis sollicitudin. Nam sagittis, velit sit amet fermentum imperdiet, mauris nulla convallis odio, ut suscipit diam magna vitae enim. Donec sed nulla eu ante vestibulum congue placerat a turpis. Maecenas sodales massa sed dolor suscipit, ac varius elit semper. Nulla consequat luctus libero non porta. In nisl diam, semper vel bibendum ac, porttitor ut nisi. Donec lobortis, quam tincidunt tristique pulvinar, eros velit egestas metus, vel consequat erat orci nec nunc. Nam ex erat, mollis sed dictum nec, aliquet suscipit leo. Donec tristique diam vel erat placerat, vel mollis turpis maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nullam nibh tellus, malesuada a dapibus id, dictum et purus. Aliquam erat volutpat. Aliquam erat volutpat. Donec iaculis congue pulvinar. Nunc nulla ex, vestibulum ut sagittis at, scelerisque ac mauris. Fusce ante arcu, porta congue leo et, luctus interdum odio. Morbi tincidunt erat condimentum, rhoncus leo vitae, convallis urna. Proin et sodales diam. Aliquam euismod felis et enim sagittis, eu tincidunt diam faucibus. Aenean convallis consectetur augue vel faucibus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et tempus nulla, a scelerisque ipsum. Nunc aliquet dignissim lorem, nec ultrices ex. Sed convallis sapien magna, vitae consectetur urna tincidunt eget. Ut pharetra risus ac pulvinar tristique. Curabitur placerat lobortis orci, id lacinia nibh porta a. Nullam convallis dolor vel mi aliquet, vel dignissim est pharetra. Sed maximus turpis metus, ultricies congue tortor accumsan eu. Mauris quis congue odio, et suscipit tortor. Vestibulum vel commodo orci. Etiam nec quam eu tortor mollis pellentesque ut id felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Aliquam nunc dui, accumsan et accumsan at, lobortis ut elit. Proin vitae velit vestibulum mi aliquam maximus. In tincidunt lacinia nulla ut pharetra. Mauris pulvinar ipsum vel nunc interdum, sed cursus risus aliquet. Aenean egestas mollis feugiat. Nam auctor risus ultrices nibh pellentesque, aliquet dapibus tellus faucibus. Nulla mollis odio vitae urna tristique blandit. Integer ac scelerisque nisi. Cras cursus felis nisi, quis pretium neque consectetur in. Pellentesque sed eros in nisi imperdiet congue. Donec luctus fringilla commodo. Quisque sodales dapibus ipsum vitae vestibulum. Duis fermentum ligula id risus blandit, id rutrum ex faucibus. Nunc sit amet mi et ipsum malesuada imperdiet eu a felis. Vestibulum sem nibh, laoreet at lectus et, commodo gravida felis.

Nullam sed auctor libero. Nulla facilisi. Sed sit amet sagittis libero. Sed massa purus, eleifend in lorem in, egestas consequat nisl. Fusce nec rhoncus turpis. Suspendisse pretium hendrerit libero, a bibendum arcu pretium bibendum. Integer lobortis facilisis aliquam. Proin scelerisque quis sem ac pulvinar. Sed ac lorem et justo varius bibendum. Proin ut maximus turpis.

Integer quis justo ac ante pretium rhoncus ut ut arcu. Integer eu auctor metus, volutpat dictum tortor. Curabitur scelerisque sem ac lacus luctus blandit. Praesent sed dignissim turpis. Curabitur pretium magna at nisi laoreet, sit amet consequat odio dictum. Duis elementum pretium vehicula. Ut sodales tortor a felis vulputate, sit amet vehicula est sodales. Phasellus id ante fermentum, mattis eros non, tincidunt odio.

Vivamus eu metus gravida, efficitur magna eu, ullamcorper tortor. Duis laoreet venenatis finibus. Aliquam vitae luctus ante. Phasellus mattis sagittis purus iaculis cursus. Suspendisse sit amet libero sit amet dolor tristique tristique. Praesent id orci felis. Fusce ut laoreet augue. Morbi commodo non nisl nec pellentesque. Pellentesque at justo ultricies, lacinia tellus eu, semper odio. Maecenas nec lacus sollicitudin, dictum tellus in, condimentum est.

Nunc in nisl ut dui facilisis condimentum nec eget eros. Vestibulum ac nunc vitae nisi commodo ultricies. Aliquam porttitor vitae dui id bibendum. Nam erat erat, pulvinar id lacus ac, commodo pharetra augue. Sed viverra est non sagittis molestie. Maecenas ullamcorper mi quis ligula dapibus, ut cursus erat vestibulum. Vestibulum a gravida leo, sit amet molestie velit. In ut ex quis magna feugiat volutpat vel vel nisl. Suspendisse viverra vel tortor quis dignissim. Donec sollicitudin commodo enim quis lacinia. Cras efficitur risus eget elit pellentesque, sed tristique nunc convallis. Donec facilisis consequat elit.

Nullam molestie blandit ligula a scelerisque. Nam vel malesuada urna. Curabitur bibendum sapien dolor, eu mattis felis accumsan sit amet. Nunc at enim eu nulla condimentum tempor. Etiam in risus eu erat varius varius nec ut odio. Aliquam nisi turpis, dictum in pellentesque vitae, vulputate at dui. Integer vel elit facilisis, ullamcorper turpis non, sollicitudin diam. Duis quis rutrum augue. Proin vel purus tincidunt, aliquam velit et, mattis orci. Proin condimentum est ac elementum porta. Suspendisse vel arcu dictum, efficitur sem a, venenatis massa. Sed ut sollicitudin augue. Donec consequat aliquet vestibulum. In hac habitasse platea dictumst. Ut bibendum tincidunt dolor in luctus.

Nunc leo est, ultricies in libero quis, malesuada feugiat velit. Mauris rutrum, sapien vitae cursus hendrerit, metus eros mattis urna, eget imperdiet sapien sapien quis erat. Quisque molestie odio nisl, et porttitor arcu molestie eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla non interdum ex, ut volutpat urna. Phasellus porttitor lacinia ipsum non varius. Quisque viverra vestibulum lectus vitae auctor. Phasellus condimentum efficitur ipsum quis molestie.

Pellentesque sed sapien vel velit laoreet sollicitudin vitae et nunc. Praesent feugiat ullamcorper fringilla. Duis mattis mattis ligula. Nunc a dictum sapien, at laoreet leo. Morbi suscipit mauris eu ultricies volutpat. Nulla consequat auctor efficitur. Duis placerat odio non pretium pharetra. Vivamus eu porta ante, eu tristique turpis. Sed ut pretium nunc. Aenean dictum purus eget purus finibus, quis lacinia ligula varius. Etiam ex libero, consectetur et ante non, semper dictum orci. Vivamus dignissim, velit vel facilisis blandit, nisl lorem vulputate dui, eu accumsan lorem mauris vel ex. Vivamus dui ante, scelerisque a erat a, congue auctor nulla. Quisque diam justo, luctus quis posuere eget, pellentesque non arcu. Aliquam euismod nec est nec gravida.

Donec sed massa neque. Suspendisse quis tincidunt eros, eu congue nisl. Nullam sagittis velit id arcu tempor, at dictum dui blandit. Quisque sapien sem, facilisis vel risus quis, ultrices iaculis nunc. Integer et orci at eros commodo consequat eu ac erat. Cras pellentesque ornare porta. Nunc mattis massa facilisis tincidunt viverra. Quisque id nunc sit amet orci viverra tincidunt a id sapien. Fusce sodales ut urna porttitor rutrum. Nunc sit amet est in nisi tempus viverra. Proin eu malesuada nulla, et sodales risus. Aenean ac sapien ac massa porta molestie vitae ac elit. Aliquam et velit id nulla consectetur vestibulum. ";
    }
}
